spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mssc_beer_works?currentSchema=mssc_beer_inventory_service&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: postgres

  artemis:
    user: artemis
    password: artemis
    broker-url: tcp://artemis:61616/