spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}?currentSchema=mssc_beer_inventory_service&binaryTransfer=true&reWriteBatchedInserts=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}